### ISSUE TITLE
Propose CI/CD setup

### ISSUE THREAD

**Issue by vitaliimelnychuk** [WiseEngineering/crispy#4]
We have 3 basic components:
- `crispy-web`
- `crispy-api`
- `crispy-worker`

Once they have the initial setup we need docker based environment setup there and CI setup as well
(can be developed with Github Actions)

**Comment by xTNTx** [comment]
Will `Github Actions` be sufficient enough? I haven't used it yet so not sure how much it provides. Since all `crispy` repos are public we may also use 'open source' plans of comercial CI/CD services such as TravisCI or CIrcleCI. Gitlab CI is also an option.

**Comment by vitaliimelnychuk** [comment]
it's a good catch!
I didn't realize GitHub doesn't provide any benefits for public repositories.

I've done some research. 
here are plan pages from Circle and Travis:
https://travis-ci.com/plans
https://circleci.com/open-source/

Since CircleCI has a strange calculation system based on users and credits, I am thinking about using Travis at all.
> We love Open Source and offer a free plan for your projects. You will receive unlimited builds and 3 concurrent jobs for free, along with all the other features you've come to love from Travis CI.

**Comment by xTNTx** [comment]
I've used both Circle and Travis very lightly so haven't got big issues with any of them.

There is some feedback out there about Circle beeing more flexible - https://stackshare.io/tabbott/decisions/101897486541876212
Also on their OSS plan I can see:
> Organizations on our free plan get 400,000 free credits per month ($2,880 annual value) to use for Linux open source builds. Keep your repo public for access.

Don't have a strong opinion so any option works for me.

**Comment by vitaliimelnychuk** [comment]
@WiseEngineering/open-source I believe, both are good for us, started with circleci: https://github.com/WiseEngineering/crispy-cli/pull/16

let me know if there is something else we have to think of
